# Generated by Django 3.2.13 on 2022-05-03 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('waiter', 'Waiter'), ('barman', 'Barman'), ('chef', 'Chef')], help_text='Job function within restaurant', max_length=25, verbose_name='Job role (title)')),
                ('bio', models.TextField(blank=True, help_text='Short biography about employee', max_length=500, verbose_name='Biography')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly salary in space £', max_digits=7, verbose_name='Monthly Salary')),
                ('location', models.CharField(blank=True, help_text='Location of residence on the planet Dentrass', max_length=100, verbose_name='Location (Address)')),
                ('dob', models.DateField(blank=True, help_text='Date of birth based on something (??)', null=True, verbose_name='Date of birth')),
                ('job_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('off duty', 'Off-duty')], max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
