# Generated by Django 3.2.13 on 2022-05-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(choices=[('a1', 'a1'), ('a2', 'a2'), ('a3', 'a3')], max_length=2)),
                ('seat_capacity', models.IntegerField(default=8, verbose_name='Table Max Chair Capacity')),
                ('order_served', models.BooleanField(default=False)),
                ('is_full', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True, help_text='Is the table available to customers')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat', to='customers.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tables.table')),
            ],
        ),
    ]
