# Generated by Django 3.2.13 on 2022-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='order_served',
        ),
        migrations.AlterField(
            model_name='table',
            name='seat_capacity',
            field=models.IntegerField(default=8, verbose_name='Max Seat Capacity'),
        ),
    ]
