# Generated by Django 3.2.13 on 2022-05-03 00:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rateotu.utils.menus


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], help_text='Food or drink', max_length=255)),
                ('slug', models.SlugField(help_text='SEO friendly URL path param (needed on the client apps)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', max_length=500)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, help_text='Menu item thumbnail URL', null=True, upload_to=rateotu.utils.menus.get_menu_item_img_dir_upload_path)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Food or drink description', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in space £', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('available_quantity', models.PositiveIntegerField(default=1, help_text='If a customer orders a multiple of the same food or drink,\n                     or for a pre made food and drinks which can be served in\n                     restaurants (e.g. cans of something, sweets, etc)')),
                ('is_active', models.BooleanField(default=True, help_text='Discontinued or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menus.category')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Menu description', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(related_name='menus', to='menus.Item')),
            ],
            options={
                'verbose_name': 'Menus',
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
